Repository bounswe/bounswe2022group7, pull requests merged in 2022-05, with the labels that each got.

#138 Initial Files for Practice App
  practice-app/.gitignore
  practice-app/README.md
Labels: Status: Pending Review

#153 Merge practice-app/database-base to backend-base
  practice-app/website/models.py
Labels: Priority: Low, Difficulty: Easy

#154 Merge practice-app/front-end-base branch into practice_app branch
  practice-app/website/templates/base.html
  practice-app/website/templates/create_event.html
  practice-app/website/templates/entry_pool.html
  practice-app/website/templates/view_and_post_to_specific_entry.html
  practice-app/website/templates/view_art_item.html
  practice-app/website/templates/view_event.html
  practice-app/website/templates/wikipedia_definition.html
Labels: Status: In Progress, Difficulty: Medium

#155 Practice app/backend base
  practice-app/requirements.txt
  practice-app/website/__init__.py
  practice-app/website/auth.py
  practice-app/website/models.py
Labels: Status: In Progress, Difficulty: Medium

#159 Merge "events" feature branch into practice-app branch
  practice-app/website/__init__.py
  practice-app/website/api/event.py
  practice-app/website/models.py
  practice-app/website/templates/base.html
  practice-app/website/templates/create_event.html
  practice-app/website/templates/view_event.html
  practice-app/website/views.py
Labels: Status: Pending Review, Priority: High, Difficulty: Medium

#167 Merge event feature branch into the practice_app
  practice-app/website/__init__.py
  practice-app/website/api/event.py
  practice-app/website/api/home.py
  practice-app/website/models.py
  practice-app/website/templates/base.html
  practice-app/website/templates/create_event.html
  practice-app/website/templates/home.html
  practice-app/website/templates/view_event.html
  practice-app/website/test/__init__.py
  practice-app/website/test/test_event.py
Labels: Status: Pending Review, Difficulty: Medium, Type: Implementation

#178 Add Docker files
  practice-app/.gitignore
  practice-app/Dockerfile
  practice-app/docker-compose.yml
Labels: Status: Completed, Difficulty: Easy

#179 Front-end Token Design
  practice-app/requirements.txt
  practice-app/website/__init__.py
  practice-app/website/api/auth.py
  practice-app/website/api/event.py
  practice-app/website/api/jwt.py
  practice-app/website/jwt.py
  practice-app/website/models.py
  practice-app/website/templates/base.html
  practice-app/website/templates/create_event.html
  practice-app/website/templates/login.html
  practice-app/website/templates/signup.html
  practice-app/website/templates/view_event.html
  practice-app/website/views.py
Labels: Status: In Progress, Priority: High, Difficulty: Hard, Type: Implementation

#193 Merge practice-app/feature/art-items to practice_app
  practice-app/requirements.txt
  practice-app/website/__init__.py
  practice-app/website/api/art_item.py
  practice-app/website/api/doc/art_item_GET.yml
  practice-app/website/api/doc/art_item_POST.yml
  practice-app/website/settings.py
  practice-app/website/templates/base.html
  practice-app/website/templates/create_art_item.html
  practice-app/website/templates/view_art_item.html
  practice-app/website/views.py
Labels: Status: Pending Review, Priority: High, Type: Implementation

#206 Art Item unit tests are also completed, merge to practice_app
  practice-app/website/templates/home.html
  practice-app/website/test/test_art_item.py
Labels: Status: Pending Review, Priority: Medium, Difficulty: Easy

#215 Merge Practice app/feature/discussion_comments into practice_app
  practice-app/website/api/discussion_forum.py
  practice-app/website/api/doc/discussion_post_comments_GET.yml
  practice-app/website/api/doc/forum_comment_POST.yml
  practice-app/website/models.py
  practice-app/website/settings.py
  practice-app/website/templates/base.html
  practice-app/website/templates/forum_post.html
  practice-app/website/test/test_discussion_comments.py
  practice-app/website/views.py
Labels: Status: Pending Review, Difficulty: Easy

#227 Practice app/feature/verification1.2
  practice-app/app.py
  practice-app/website/__init__.py
  practice-app/website/api/doc/request_verification_POST.yml
  practice-app/website/api/doc/review_verification_request_POST.yml
  practice-app/website/api/doc/verification_request_GET.yml
  practice-app/website/api/event.py
  practice-app/website/api/home.py
  practice-app/website/api/verification.py
  practice-app/website/models.py
  practice-app/website/settings.py
  practice-app/website/templates/base.html
  practice-app/website/templates/bootstrap.html
  practice-app/website/templates/home.html
  practice-app/website/templates/request_verification.html
  practice-app/website/templates/signup.html
  practice-app/website/templates/view_verification_request.html
  practice-app/website/test/test_verification.py
  practice-app/website/views.py
Labels: Status: Pending Review, Priority: High, Difficulty: Medium, Type: Implementation

#216 Merge participants feature to main branch
  .github/workflows/AWS-Deployment.yml
  practice-app/docker-compose.yml
  practice-app/website/__init__.py
  practice-app/website/api/doc/participants_DELETE.yml
  practice-app/website/api/doc/participants_GET.yml
  practice-app/website/api/doc/participants_POST.yml
  practice-app/website/api/doc/participants_share_POST.yml
  practice-app/website/api/participants.py
  practice-app/website/templates/participate.html
  practice-app/website/test/test_participants.py
  practice-app/website/views.py
Labels: Status: Pending Review, Priority: High

#201 Practice app/feature/copyright
  practice-app/website/__init__.py
  practice-app/website/api/copyright.py
  practice-app/website/api/doc/copyright_DELETE.yml
  practice-app/website/api/doc/copyright_GET.yml
  practice-app/website/api/doc/copyright_POST.yml
  practice-app/website/api/home.py
  practice-app/website/models.py
  practice-app/website/settings.py
  practice-app/website/templates/base.html
  practice-app/website/templates/home.html
  practice-app/website/templates/report_infringement.html
  practice-app/website/templates/view_copyright_report.html
  practice-app/website/test/test_copyright.py
  practice-app/website/views.py
Labels: Status: Pending Review, Priority: High, Difficulty: Medium

#234 Merge practice-app/feature/discussion-comments into practice_app
  practice-app/website/api/discussion_forum.py
  practice-app/website/test/test_discussion_comments.py
Labels: Status: Pending Review, Priority: High, Difficulty: Easy
